<?php

declare(strict_types=1);

namespace AltenJohn\CrudGenerator\Commands;

use AltenJohn\CrudGenerator\Definitions\CrudDefinition;
//use AltenJohn\CrudGenerator\Definitions\CrudFileDefinitions;
use AltenJohn\CrudGenerator\Support\CrudName;
use Illuminate\Console\Command;
//use Illuminate\Support\Str;

final class DeleteCrudCommand extends Command
{
    protected $signature = 'delete:crud
        {name : CRUD name, for example V1/Product}
        {--force : Delete without confirmation}
        {--dry-run : Show files that would be deleted without deleting them}';

    protected $description = 'Delete files generated by the CRUD generator';

    public function __construct() 
    {
        parent::__construct();
    }

    public function handle(): int
    {
        $crud = CrudName::from(
            $this->argument('name'),
        );

        $replacements = $this->buildReplacements($crud);

        $definitions = CrudDefinition::definitions();
      //  $files = $this->definitions->forDeletion();

        $paths = [];

        foreach ($definitions as $definition) {

            // Migration tidak ikut dihapus
            if ($definition->option === 'migration') {
                continue;
            }




            $paths[] = $this->buildPath(
                $definition->directory,
                $definition->filename,
                $definition->crud,
                $replacements,
            );
        }

        if ($paths === []) {
            $this->warn('No files configured for deletion.');

            return self::SUCCESS;
        }

        $existingPaths = array_values(
            array_filter(
                $paths,
                file_exists(...),
            ),
        );

        if ($existingPaths === []) {
            $this->warn('No generated files found.');

            return self::SUCCESS;
        }

        $this->newLine();
        $this->info('The following files will be deleted:');
        $this->newLine();

        foreach ($existingPaths as $path) {
            $this->line('  '.$path);
        }

        $this->newLine();

        $count = count($existingPaths);

        if ($this->option('dry-run')) {
            
            

            $this->comment(
                "Dry run completed. {$count} file(s). No files were deleted."
                
                );

            return self::SUCCESS;
        }

        if (
            ! $this->option('force')
            && ! $this->confirm("Do you want to continue Delete {$count} file(s)?", false)
        ) {
            $this->warn('Deletion cancelled.');

            return self::SUCCESS;
        }

        $deleted = 0;
        $failed = 0;

        foreach ($existingPaths as $path) {
            if (@unlink($path)) {
                $deleted++;

                $this->info(
                    '✓ Deleted '.$path,
                );

                continue;
            }

            $failed++;

            $this->error(
                '✗ Failed to delete '.$path,
            );
        }

        $this->deleteEmptyDirectories($crud);

        $this->newLine();

        if ($failed > 0) {
            $this->error(
                "Deletion completed with errors. Deleted: {$deleted}, Failed: {$failed}.",
            );

            return self::FAILURE;
        }

        $this->info(
            "CRUD deleted successfully. Files deleted: {$deleted}.",
        );

        return self::SUCCESS;
    }

    /**
     * @return array<string, string>
     */
    private function buildReplacements(CrudName $crud): array
    {
        return [
            '{{ model }}' => $crud->model,
            '{{ variable }}' => $crud->variable(),
            '{{ table }}' => $crud->table(),
            '{{ path }}' => $crud->version,
            '{{ route_path }}' => $crud->routePath(),
            '{{ controller }}' => $crud->path(),
            '{{ controller_namespace }}' => $crud->controllerNamespace(),
        ];
    }

    /**
     * Build the generated file path.
     *
     * @param array<string, string> $replacements
     */
    private function buildPath(
        string $directory,
        string $filename,
        string $crud,
        array $replacements,
    ): string {
        $replacements['{{ crud }}'] = $crud;

        $directory = str_replace(
            array_keys($replacements),
            array_values($replacements),
            $directory,
        );

        $filename = str_replace(
            array_keys($replacements),
            array_values($replacements),
            $filename,
        );

        return base_path(
            trim($directory.'/'.$filename, '/'),
        );
    }

    private function deleteEmptyDirectories(CrudName $crud): void
    {
        $directories = [
            base_path('app/Actions/'.$crud->model),
            base_path('app/DTOs/'.$crud->model),
            base_path('app/Http/Controllers/Api/'.$crud->path()),
            base_path('tests/Feature/Api/'.$crud->path()),
        ];

        foreach ($directories as $directory) {
            if (
                is_dir($directory)
                && $this->isDirectoryEmpty($directory)
            ) {
                rmdir($directory);
            }
        }
    }

    private function isDirectoryEmpty(string $directory): bool
    {
        $files = scandir($directory);

        if ($files === false) {
            return false;
        }

        return count($files) === 2;
    }
}
